source 'https://rubygems.org'
ruby '2.3.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'haml-rails'
gem 'mysql2', '0.3.20'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'bootstrap', '~> 4.0.0.alpha6'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'devise'

  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'simplecov'
  gem 'countdown'
  gem 'simple_form'
end
